trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '*/surefire-reports/TEST-.xml'